name: Bug Report
description: Tell us about unexpected behavior from hbupdater.
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug!
  - type: input
    id: version
    attributes:
      label: Software Version
      description: Version
      placeholder: e.g. 0.1.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What Happened?
      description:
        Describe the Bug. Optionally, add screenshots (or exception logs, if
        applicable) to help with our understanding of the issue.
      placeholder: A bug happened!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was Expected?
      description:
        Describe what should happen. Optionally, add screenshots to help with
        our understanding of what is expected.
      placeholder: The bug shouldn't happen!
    validations:
      required: true
