name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: make
  
  macOS:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: make

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make
