name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.3.54

      - run: nimble build -Y

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Windows-${{ steps.commit.outputs.short }}
          path: dist/*

  macOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.3.54

      - run: nimble build -Y

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: macOS-${{ steps.commit.outputs.short }}
          path: dist/*

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: commit
      uses: pr-mpt/actions-commit-hash@v1

    - name: Setup Nim environment
      uses: jiro4989/setup-nim-action@v1.3.54

    - run: nimble build -Y

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: Linux-${{ steps.commit.outputs.short }}
        path: dist/*
